import type { NextPage } from 'next'
import Head from 'next/head'
import Home from '@components/Home'
import Test from '@components/Test'
import FeedbacksList from '@components/Feedback/FeedbacksList'
import UsersList from '@components/Github/UsersList'

const HomePage: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Next Tailwind</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			{/* <Home />
			<Test /> */}
			{/* <FeedbacksList /> */}
			<UsersList />
		</div>
	)
}

export default HomePage
